create table account (id bigint not null auto_increment, password varchar(255), status varchar(255), username varchar(255), eid bigint, roleid bigint, primary key (id)) engine=InnoDB;
create table account_event_rel (id bigint not null auto_increment, accountid bigint, eventid bigint, primary key (id)) engine=InnoDB;
create table attendance (id bigint not null auto_increment, date date, eid bigint, primary key (id)) engine=InnoDB;
create table bonus_list (id bigint not null auto_increment, amount decimal(16,2), bonus_name varchar(255), eid bigint, primary key (id)) engine=InnoDB;
create table candidate (id bigint not null auto_increment, applied_date date, contact varchar(255), cv_file TEXT, date_of_birth date, email varchar(255), name varchar(255), job_recruitment_id bigint, primary key (id)) engine=InnoDB;
create table checkin (attendance_id bigint not null, date date, device_id varchar(255), status integer, time_in time, time_out time, primary key (attendance_id)) engine=InnoDB;
create table department (id bigint not null auto_increment, description TEXT, location varchar(255), name varchar(255), people_number integer, type varchar(255), head_of_unit_id bigint, primary key (id)) engine=InnoDB;
create table employee (id bigint not null auto_increment, avatar TEXT, date_of_birth date, email varchar(255), employed_date date, first_name varchar(255), gross_salary decimal(16,2), last_name varchar(255), permanent_address varchar(255), phone varchar(255), pit varchar(255), sex varchar(255), temporary_address varchar(255), position_id bigint, shift_id bigint, primary key (id)) engine=InnoDB;
create table event (id bigint not null auto_increment, location varchar(255), notes TEXT, time datetime(6), time_end datetime(6), title varchar(255), type varchar(255), primary key (id)) engine=InnoDB;
create table has (id bigint not null auto_increment, jrecruitid bigint, posid bigint, primary key (id)) engine=InnoDB;
create table insurance (eid bigint not null, typeid bigint not null, city_id bigint, from_date date, issue_date date, kcb_id bigint, number varchar(255), to_date date, primary key (eid, typeid)) engine=InnoDB;
create table insurance_type (id bigint not null auto_increment, name varchar(255), rate_of_payment decimal(16,2), primary key (id)) engine=InnoDB;
create table job_recruitment (id bigint not null auto_increment, expired_date date, note TEXT, post_content TEXT, published_date date, quantity integer, status integer, department_id bigint, hiring_manager_id bigint, primary key (id)) engine=InnoDB;
create table leave_type (id bigint not null auto_increment, is_paid bit, name varchar(255), primary key (id)) engine=InnoDB;
create table leaves (id bigint not null auto_increment, application_date date, from_date date, reason TEXT, status integer, to_date date, total integer, eid bigint, typeid bigint, primary key (id)) engine=InnoDB;
create table manage (did bigint not null, eid bigint, primary key (did)) engine=InnoDB;
create table managed_by (eid bigint not null, pid bigint, primary key (eid)) engine=InnoDB;
create table noti_expo_tokens (id bigint not null auto_increment, expo_noti_token TEXT, primary key (id)) engine=InnoDB;
create table payment (id bigint not null auto_increment, actual_day varchar(255), allowance_not_subjected_to_tax decimal(16,2), basic_salary decimal(16,2), dependent_relief decimal(16,2), lunch decimal(16,2), paid_leave varchar(255), parking decimal(16,2), payment_date date, personal_relief decimal(16,2), standard_day varchar(255), total_bonus decimal(16,2), unpaid_leave varchar(255), eid bigint, payroll_id bigint, primary key (id)) engine=InnoDB;
create table payroll (id bigint not null auto_increment, created_time date, name varchar(255), primary key (id)) engine=InnoDB;
create table performs (eid bigint not null, taskid bigint not null, pid bigint not null, primary key (eid, taskid, pid)) engine=InnoDB;
create table position (id bigint not null auto_increment, description varchar(255), max_salary decimal(16,2), min_salary decimal(16,2), name varchar(255), note varchar(255), salary_group integer, primary key (id)) engine=InnoDB;
create table project (id bigint not null auto_increment, end_date date, name varchar(255), start_date date, primary key (id)) engine=InnoDB;
create table role (id bigint not null auto_increment, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table shift (id bigint not null auto_increment, name varchar(255), time_in time, time_out time, primary key (id)) engine=InnoDB;
create table task (id bigint not null auto_increment, pid bigint not null, content TEXT, status varchar(255), title varchar(255), primary key (id, pid)) engine=InnoDB;
create table works_in (eid bigint not null, did bigint, primary key (eid)) engine=InnoDB;
create table works_on (hours bigint, eid bigint not null, pid bigint, primary key (eid)) engine=InnoDB;
alter table account add constraint FK2neav5gsa773rwxay6s0ib9q2 foreign key (eid) references employee (id);
alter table account add constraint FK4uk2u5ju46nwjwvlwt1jol9ue foreign key (roleid) references role (id);
alter table account_event_rel add constraint FK7j2d8249dds50vnrw07u5vow7 foreign key (accountid) references account (id);
alter table account_event_rel add constraint FK6vs6aojrwiqju9i6inx3txnl2 foreign key (eventid) references event (id);
alter table attendance add constraint FK1ja4jj07t8co2pc74j0ckl59o foreign key (eid) references employee (id);
alter table bonus_list add constraint FK8oexta4kt1gvxjws78vpwakqg foreign key (eid) references employee (id);
alter table candidate add constraint FKt1kyp9xadlan1r2rrg0samsps foreign key (job_recruitment_id) references job_recruitment (id);
alter table checkin add constraint FKrfro7kgmdnscow8ee5hpr34oc foreign key (attendance_id) references attendance (id);
alter table department add constraint FKhwihkrs21tavvykrih45c9oit foreign key (head_of_unit_id) references department (id);
alter table employee add constraint FKbc8rdko9o9n1ri9bpdyxv3x7i foreign key (position_id) references position (id);
alter table employee add constraint FKsa116m61em4801vxsd98mnr50 foreign key (shift_id) references shift (id);
alter table has add constraint FKghjm0yqnsb5lu2f63t7f3lv67 foreign key (jrecruitid) references job_recruitment (id);
alter table has add constraint FKfctdmqapnhx5204em7ea0nmbf foreign key (posid) references position (id);
alter table insurance add constraint FK3s3edx1le2u73ceh5hcscjao5 foreign key (eid) references employee (id);
alter table insurance add constraint FKi83dhq4dn9sxbs6v624q0jl07 foreign key (typeid) references insurance_type (id);
alter table job_recruitment add constraint FKhwaqfnj5mjv0twvqkx9b9o4ns foreign key (department_id) references department (id);
alter table job_recruitment add constraint FKiqels1jv7x9lfdhauvdrn9c1k foreign key (hiring_manager_id) references employee (id);
alter table leaves add constraint FKct2jmtn0m6gdq018w4t66y3w9 foreign key (eid) references employee (id);
alter table leaves add constraint FKpyycia4cuurr3fn7cn6os11lv foreign key (typeid) references leave_type (id);
alter table manage add constraint FKlhjwqsk9r98rx5kfgnimr620t foreign key (eid) references employee (id);
alter table manage add constraint FKjym3vfmonec4p0qyovpkr303a foreign key (did) references department (id);
alter table managed_by add constraint FK5jbgfkpi0w11whfw39ngesvsv foreign key (eid) references employee (id);
alter table managed_by add constraint FKorh3tnkytl3j2gvctrhlhd7eu foreign key (pid) references project (id);
alter table payment add constraint FKklurhil02yqllonk5y5qrl7xc foreign key (eid) references employee (id);
alter table payment add constraint FK84wnkhdh937ks551e1t55gic6 foreign key (payroll_id) references payroll (id);
alter table performs add constraint FK12hsevbq0rlluntg4tbiubm5g foreign key (taskid, pid) references task (id, pid);
alter table performs add constraint FKca4msxgcdy705j4pu5dvfgbwt foreign key (eid) references employee (id);
alter table task add constraint FK6lcyxw45rx12wikvofewqfeb0 foreign key (pid) references project (id);
alter table works_in add constraint FK5du22ku3v4gm4ojenmctj4kl6 foreign key (did) references department (id);
alter table works_in add constraint FKbcjs5q943wf0k4ubptpyy5an2 foreign key (eid) references employee (id);
alter table works_on add constraint FKoascll1lfe51f8720y2eno809 foreign key (eid) references employee (id);
alter table works_on add constraint FKmn2hncgm84lm1dpgosbh6x6bm foreign key (pid) references project (id);
